### ISSUE TITLE
iPod touch 6 

### ISSUE THREAD

**Issue by emb3625** [dkun7944/pitch-ios#1]
The iPod touch 6 has very spotty accuracy with the tuning app. I love the interface, but it's just inaccurate with my device. I've tried installing and reinstalling, updating, and nothing. Very rarely does it "stick" to telling me whether a sustained note is in tune or not. I'd really appreciate it if you could check into this to see if the issue can be fixed.

**Comment by dkun7944** [comment]
@emb3625 What instrument do you play?

**Comment by emb3625** [comment]
I play trombone. However, I know it's not just a "me" issue because I know other players that wanted me to tune them, including clarinet and alto/tenor sax players, and the same thing happens with them (on my device).

**Comment by emb3625** [comment]
@dkun7944 by the way thank you for the fast support! Literally have never gotten such a fast response for an issue (for anything!)!

**Comment by dkun7944** [comment]
@emb3625 No prob! Have you pulled the latest commit? I just added a 'response speed' setting. Setting it to 'slow' or 'normal' might clear things up. Let me know if this works. This should be up on the App Store in a few days too.

**Comment by emb3625** [comment]
I actually am currently using the App Store version (mainly because I'm a noob and can't compile apps cause I have no Mac), so no. I will definitely try that once the new version comes out (unless you have a TestFlight beta that could give me quicker access… 🤔)!

**Comment by dkun7944** [comment]
@emb3625 Send me an email and I'll add you to the TestFlight. dkuntz0@gmail.com

**Comment by emb3625** [comment]
Sent! Thank you!
